### ISSUE TITLE
use constants for magic numbers

### ISSUE THREAD

**Issue by incredibleLeitman** [nsofiia/guess_game#2]
https://github.com/nsofiia/guess_game/blob/3d53588d6d890a0f5f2a18f39506e1f37989b797/guessGame/Program.cs#L13-L16

the amount of tries should be a constant so that you only have one place to change the behavior.
The same applies for the random bounds between which the random number can be

**Comment by nsofiia** [comment]
not clear which variable is expected to be const, when changing to const any of them - errors are thrown

**Comment by incredibleLeitman** [comment]
"the amount of tries" which is your 3.

You go straight to the wall of shame if you write that errors are thrown but no further explanation such as error message or code 👆

**Comment by nsofiia** [comment]
@incredibleLeitman 
here is the error returned when I switch wrong guess counter to constant value.
<img width="1082" alt="Screen Shot 2022-11-24 at 4 18 13 PM" src="https://user-images.githubusercontent.com/88280676/203869786-fd3ad660-6a80-4d5d-aaf9-a1f543296d4b.png">
<img width="340" alt="Screen Shot 2022-11-24 at 4 18 25 PM" src="https://user-images.githubusercontent.com/88280676/203869800-8af85399-6b76-4ecb-b5da-2b67982c6d5d.png">

I am using this value in the loop and decrementing with each wrong guess

**Comment by incredibleLeitman** [comment]
- const variables should be in ALL_UPPER_CASE and outside of your function
- yeah const means exactly this, that you cannot modify the value afterwards :D
what you want to do is setting your variable to the constant like
```
int wrongGuessCount = MAX_GUESSES
```

**Comment by incredibleLeitman** [comment]
As I mentioned, constants should go outside of your function ☝️ 

the structure looks like 
```
// all your usings

namespace yourNamespace
{
  class yourClass
  {
    **// here belong your global variables and constants**

    Main ()
    {
      // your code goes here
    }
  }
}
```

The reason for having constants outside of your function is, that you can reuse them,
for setting values and printing infos
as well as in other functions or classes (we come to that later)

**Comment by nsofiia** [comment]
@incredibleLeitman this is fixed (hopefully)
