### ISSUE TITLE
"You're close!" does not work as expected

### ISSUE THREAD

**Issue by incredibleLeitman** [nsofiia/guess_game#5]
There are a few flaws in this code:

https://github.com/nsofiia/guess_game/blob/3d53588d6d890a0f5f2a18f39506e1f37989b797/guessGame/Program.cs#L27-L31

1. you only check, if the guessed value is equal to the random number +/- 5, which means, for example when the randomNumer is 10 and the user guesses 15 -> gets printed, but if 11 is guessed, there is no print even though its even closer 🤷 

https://github.com/nsofiia/guess_game/blob/3d53588d6d890a0f5f2a18f39506e1f37989b797/guessGame/Program.cs#L11-L12

2. Do you really need those 2 variables? There is at least one other way you could write the same functionality without the need of two extra variables. Maybe take a look at the Math.Abs function https://learn.microsoft.com/de-de/dotnet/api/system.math.abs?view=net-7.0 and think, how you could use it to check if the user is close

3. You are increasing "wrongGuesses" additionally when the users guess is close, is this intentional?

4. The block where the check if the user is close is duplicated. You should always try to reuse code instead of copy pasting it to make your codebase easier to maintain and less error prone.

**Comment by f-rakete** [comment]
@nsofiia as far as I can see, none of the issues are actually addressed
