### ISSUE TITLE
Check if the user is close by using the difference instead of two checks

### ISSUE THREAD

**Issue by incredibleLeitman** [nsofiia/guess_game#6]
https://github.com/nsofiia/guess_game/blob/fa2289f358952082926901283ff615f89ad97407/guessGame/Program.cs#L15-L16

https://github.com/nsofiia/guess_game/blob/fa2289f358952082926901283ff615f89ad97407/guessGame/Program.cs#L38

You could use the difference between both values to check if the user is close. Presumably you'll need Math.Abs for this:
https://learn.microsoft.com/en-us/dotnet/api/system.math.abs?view=net-7.0

**Comment by nsofiia** [comment]
@incredibleLeitman 

I might be not smart enough.

Looked at a few sources of info with Math.Abs(), 
still didn't understand 
how can I use for `guess` comparison to `closeMinus and closePlus`,
using the Math.Abs()

**Comment by incredibleLeitman** [comment]
No worries, this does not have to do anything with smartness ^^
If you never did something like this before, how could you possibly know? 

To check if the user is close to the guess you basically only need the difference between those two values right?
For example, if the random number is 10 and the user guesses 15 -> the difference would be 5 and "you are close" should be printed. Same goes for random number 10 and user guess 5. 
But depending on which variable you are having on the left side to calculate the difference
"guess - random" or "random - guess"
one result will be negative. To counter this, you can use Math.Abs to get the absolut value instead of the one with a sign

**Comment by nsofiia** [comment]
I am not sure how to do it.

I need to include all numbers in between the guess +5 and guess -5 as well.

tried this: 
removed initial variables and replaced them in conditional statements with following:
<img width="329" alt="Screen Shot 2022-11-25 at 4 24 49 PM" src="https://user-images.githubusercontent.com/88280676/204060170-6b929ca0-3ff6-4a76-8c27-e2ab368c80a7.png">



this change didn't work, now program is not even checking the proximity to the correct answer.

**Comment by nsofiia** [comment]
can not imagine it in 1 statement 
if guess value is between (closePlus <= guess >= closeMinus )

**Comment by nsofiia** [comment]
found this Math.Abs(nr1 - nr2)

**Comment by incredibleLeitman** [comment]
> 

yes, this is basically it :D 👍

**Comment by nsofiia** [comment]
still do not understand use for this one

**Comment by incredibleLeitman** [comment]
Currently you check if the guessed number is between the lower bound closeMinus and the upper bound closePlus. This works perfectly fine, but I just want to show you another way to solve this :D


Basically, to get the difference between two values you can just substract them:
guess - randomNumber would give you this "offset" the user is away from the correct answer. But just the substraction would result in either a positive or negative number, depending on which of those is larger. To solve this, you can use Math.Abs to get just the difference, without the sign

**Comment by nsofiia** [comment]
@incredibleLeitman understand now! thank you
